#!/usr/bin/env bash

if [[ "$(uname -s)" == "Darwin" ]]; then
    STARTDATE=$(date -v-10d +%F)
else
    STARTDATE=$(date -d "-10 days" +%F)
fi

aws ce get-cost-and-usage --time-period Start="$STARTDATE",End="$(date +%F)" --metrics "BlendedCost" "UnblendedCost" "UsageQuantity" --granularity DAILY
