#!/usr/bin/bash


if [ $# -eq 0 ]
then
  echo "No role specified"
  echo "Usage:  $0 Role"
  exit
fi


unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN

export ROLE=$1
export ACCOUNTID=$(aws sts get-caller-identity --query "Account" --output text)
export SESSIONID="awssu-$$"

export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
$(aws sts assume-role \
--role-arn arn:aws:iam::$ACCOUNTID:role/$ROLE \
--role-session-name $SESSIONID \
--query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
--output text))

# We can't pass variables back to the calling shell - but - we can pass them to a new shell.
$SHELL
