#!/usr/bin/env bash

if command -V jq >/dev/null 2>&1; then
    aws sts get-caller-identity --no-cli-pager | jq
else
    aws sts get-caller-identity --no-cli-pager
fi
# aws sts get-caller-identity --query "Arn"
