#!/usr/bin/bash
aws ec2 describe-instances --filters "Name=instance.group-name,Values=$*" --query 'Reservations[].Instances[].[InstanceId, Tags[?Key==`Name`].Value | [0]]' --output text
aws ec2 describe-instances --filters "Name=instance.group-name,Values=$*" --query 'Reservations[].Instances[].[InstanceId, Tags[?Key==`Name`].Value | [0], VpcId, VpcIdTags[?Key==`Name`].Value | [0], VpcAttributes.CidrBlock]' --output text

