#!/usr/bin/bash

aws ec2 describe-security-groups --group-ids sg-06e2f95cf48212ef2 --query 'SecurityGroups[*].IpPermissions' --output text | awk 'NR%2{printf "%s ",$0;next}1' | pr -t | egrep -v '^\s+-1'
