#!/usr/bin/env bash

StackList=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query 'StackSummaries[*].StackName' --output text)

for Stack in $StackList
do
    echo  "> Stack: $Stack"
    aws cloudformation list-stack-resources --stack-name $Stack --query 'StackResourceSummaries[*].[LogicalResourceId,ResourceType,PhysicalResourceId]'
done
